service: serverless-rest-api-with-rds

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs4.3

functions:
  get:
    handler: get.get
    events:
      - http:
          path: news/{id}
          method: get
          cors: true
